---
title: Assignment 8
author: Katy Linich
date: 7 April, 2020
output: html_notebook
---

#1-------------------------------------------------------------------------------------------------

```{r}
total_scores <- function(survey_data, scale_num, vector_num) {
  survey_matrix <- as.matrix(survey_data)
  survey_matrix[,vector_num] <- (scale_num+1) - survey_matrix[,vector_num]
  sum_total_scores <- rowSums(survey_matrix)
  survey_data$sum <- sum_total_scores
  return(survey_data)
}
```

#2-------------------------------------------------------------------------------------------------
```{r include=FALSE}
install.packages("here")
```


```{r include=FALSE}
survey_scores <- read.csv("Survey_Data.csv",
                          header = TRUE,
                          sep = ",")
```

```{r}
complete_surv_data <- total_scores(survey_scores[,2:9],5,c(3,5,8))

write.csv(complete_surv_data, file = "Final_Survey_Data.csv")

```

#3-------------------------------------------------------------------------------------------------

```{r}
install.packages("tidyverse")
library(tidyverse)
```

```{r include=FALSE}
hsb2 <- read.csv("hsb2.csv",
                 header = TRUE,
                 sep = ",")

```

```{r}
hsb_math_gender <- ggplot(hsb2, aes(math, science, color=female))

hsb_plot <- hsb_math_gender+geom_point()

hsb_plot


```

#4-------------------------------------------------------------------------------------------------

```{r}
hsb_plot+facet_wrap(~female)
```


